from abc import ABC, abstractmethod

class GenAIInterface(ABC):
    """
    Defines the "contract" that any AI interface class must follow.
    It establishes the abstract methods that concrete implementations must define.
    """

    @abstractmethod
    def __init__(self):
        """
        Constructor. Child classes can use this to initialize connections,
        load configurations, etc.
        """
        pass

    @abstractmethod
    def send_prompt(self, prompt_text: str) -> str:
        """
        Main method for sending a prompt to the language model.

        Args:
            prompt_text: The full prompt to be sent to the LLM.

        Returns:
            The text response generated by the LLM.
        """
        pass

